### ISSUE TITLE
bug: Cairo version mismatch with Madara app chain

### ISSUE THREAD

**Issue by slon2015** [kkrt-labs/kakarot#1029]
### Kakarot version

80d99d0a7451517f8c308161db318a16509ebbaa

### Current behavior

When I tried to deploy kakarot programs to Madara app chain [version](https://github.com/karnotxyz/madara/commit/b76228805c5ba21a2e5446a3f6eaec90d55cd860) the deployment script failed with log 
```                  
poetry check --lock
All set!
/Library/Developer/CommandLineTools/usr/bin/make clean
rm -rf build/*.json
rm -rf build/fixtures/*.json
mkdir -p build
poetry run python ./scripts/compile_kakarot.py
The currently activated Python version 3.12.2 is not supported by the project (>=3.9,<3.10).
Trying to find and use a compatible version. 
Using python3 (3.9.5)
INFO:scripts.constants:ℹ️  Connected to CHAIN_ID b'SN_GOERLI'
INFO:__main__:ℹ️  Compiling contracts for network madara
INFO:scripts.utils.starknet:⏳ Compiling contract_account
INFO:scripts.utils.starknet:⏳ Compiling externally_owned_account
INFO:scripts.utils.starknet:⏳ Compiling kakarot
INFO:scripts.utils.starknet:⏳ Compiling proxy
INFO:scripts.utils.starknet:⏳ Compiling EVM
INFO:scripts.utils.starknet:⏳ Compiling OpenzeppelinAccount
INFO:scripts.utils.starknet:⏳ Compiling ERC20
INFO:scripts.utils.starknet:⏳ Compiling replace_class
INFO:scripts.utils.starknet:✅ replace_class compiled in 1.97s
INFO:scripts.utils.starknet:✅ proxy compiled in 2.69s
INFO:scripts.utils.starknet:✅ ERC20 compiled in 3.23s
INFO:scripts.utils.starknet:✅ OpenzeppelinAccount compiled in 3.44s
INFO:scripts.utils.starknet:✅ contract_account compiled in 4.50s
INFO:scripts.utils.starknet:✅ externally_owned_account compiled in 7.41s
INFO:scripts.utils.starknet:✅ EVM compiled in 17.08s
INFO:scripts.utils.starknet:✅ kakarot compiled in 17.54s
INFO:__main__:✅ Compiled all in 17.57s
poetry run python ./scripts/deploy_kakarot.py
The currently activated Python version 3.12.2 is not supported by the project (>=3.9,<3.10).
Trying to find and use a compatible version. 
Using python3 (3.9.5)
INFO:scripts.constants:ℹ️  Connected to CHAIN_ID b'SN_GOERLI'
INFO:__main__:ℹ️  Using account 0x3 as deployer
INFO:scripts.utils.starknet:ℹ️  Declaring kakarot
INFO:scripts.utils.starknet:✅ Class already declared, skipping
INFO:scripts.utils.starknet:ℹ️  Declaring contract_account
INFO:scripts.utils.starknet:✅ Class already declared, skipping
INFO:scripts.utils.starknet:ℹ️  Declaring externally_owned_account
INFO:scripts.utils.starknet:✅ Class already declared, skipping
INFO:scripts.utils.starknet:ℹ️  Declaring proxy
INFO:scripts.utils.starknet:✅ Class already declared, skipping
INFO:scripts.utils.starknet:ℹ️  Declaring EVM
INFO:scripts.utils.starknet:✅ Class already declared, skipping
INFO:scripts.utils.starknet:ℹ️  Declaring OpenzeppelinAccount
INFO:scripts.utils.starknet:✅ Class already declared, skipping
INFO:scripts.utils.starknet:ℹ️  Declaring Precompiles
Traceback (most recent call last):
  File "/Users/serafimgerasimov/projects/aphotic/madara/kakarot/./scripts/deploy_kakarot.py", line 77, in <module>
    run(main())
  File "/Users/serafimgerasimov/.pyenv/versions/3.9.5/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/serafimgerasimov/.pyenv/versions/3.9.5/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/serafimgerasimov/projects/aphotic/madara/kakarot/./scripts/deploy_kakarot.py", line 34, in main
    class_hash = {
  File "/Users/serafimgerasimov/projects/aphotic/madara/kakarot/./scripts/deploy_kakarot.py", line 35, in <dictcomp>
    contract["contract_name"]: await declare(contract)
  File "/Users/serafimgerasimov/projects/aphotic/madara/kakarot/scripts/utils/starknet.py", line 394, in declare
    resp = await account.client.declare(transaction=declare_v2_transaction)
  File "/Users/serafimgerasimov/Library/Caches/pypoetry/virtualenvs/kakarot-evLp61Mw-py3.9/lib/python3.9/site-packages/starknet_py/net/full_node_client.py", line 496, in declare
    res = await self._client.call(
  File "/Users/serafimgerasimov/Library/Caches/pypoetry/virtualenvs/kakarot-evLp61Mw-py3.9/lib/python3.9/site-packages/starknet_py/net/http_client.py", line 75, in call
    self.handle_rpc_error(result)
  File "/Users/serafimgerasimov/Library/Caches/pypoetry/virtualenvs/kakarot-evLp61Mw-py3.9/lib/python3.9/site-packages/starknet_py/net/http_client.py", line 82, in handle_rpc_error
    raise ClientError(
starknet_py.net.client_errors.ClientError: Client failed with code 500. Message: Internal server error.
make: *** [deploy] Error 1
```

Madara logs

```
2024-03-12 21:11:42 Madara initialized w/o DA layer    
2024-03-12 21:11:42 Madara initialized w/o settlement layer    
2024-03-12 21:11:42 Madara Node    
2024-03-12 21:11:42 ✌️  version 0.6.0-b76228805c5    
2024-03-12 21:11:42 ❤️  by Abdelhamid Bakhta <@keep-starknet-strange>:Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2024    
2024-03-12 21:11:42 📋 Chain specification: Development    
2024-03-12 21:11:42 🏷  Node name: Alice    
2024-03-12 21:11:42 👤 Role: AUTHORITY    
2024-03-12 21:11:42 💾 Database: RocksDb at /Users/serafimgerasimov/.madara/app-chains/aphotic/data/chains/dev/db/full    
2024-03-12 21:11:42 🧪 Using the following development accounts:    
2024-03-12 21:11:42 🧪 NO VALIDATE with address: 0x1 and no pk    
2024-03-12 21:11:42 🧪 ARGENT with address: 0x2 and pk: 0xc1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d    
2024-03-12 21:11:42 🧪 OZ with address: 0x3 and pk: 0xc1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d    
2024-03-12 21:11:42 🧪 CAIRO 1 with address: 0x4 and no pk    
2024-03-12 21:11:42 Using default protocol ID "sup" because none is configured in the chain specs    
2024-03-12 21:11:42 🏷  Local node identity is: 12D3KooWNpk7jf8rcvwpH8XRFjtbaSHSewkzmCdTuSVZbMBR3r7p    
2024-03-12 21:11:42 💻 Operating system: macos    
2024-03-12 21:11:42 💻 CPU architecture: aarch64    
2024-03-12 21:11:42 📦 Highest known block at #1646    
2024-03-12 21:11:42 〽️ Prometheus exporter started at 0.0.0.0:9615    
2024-03-12 21:11:42 Running JSON-RPC server: addr=0.0.0.0:9944, allowed origins=["*"]    
2024-03-12 21:11:47 💤 Idle (0 peers), best: #1646 (0x2a82…98e5), finalized #1644 (0x7780…4056), ⬇ 0 ⬆ 0    
2024-03-12 21:11:48 🙌 Starting consensus session on top of parent 0x2a8297061d92913ba3e3b73f063cdd56a0a577145018350546d130ac02c198e5    
2024-03-12 21:11:48 🎁 Prepared block for proposing at 1647 (3 ms) [hash: 0xbfb38c49e16a4f140a8a963de182ac0728661e5ea9e804b6919b7687d9dcb621; parent_hash: 0x2a82…98e5; extrinsics (2): [0xc6b5…ba14, 0x0375…2dd6]    
2024-03-12 21:11:48 🔖 Pre-sealed block for proposal at 1647. Hash now 0xd43dc7558f1678cb40ecef97f93608186021b7b5ba05855d58270329f018dd96, previously 0xbfb38c49e16a4f140a8a963de182ac0728661e5ea9e804b6919b7687d9dcb621.    
2024-03-12 21:11:48 ✨ Imported #1647 (0xd43d…dd96)    
2024-03-12 21:11:52 💤 Idle (0 peers), best: #1647 (0xd43d…dd96), finalized #1645 (0x4432…5927), ⬇ 0 ⬆ 0    
2024-03-12 21:11:54 🙌 Starting consensus session on top of parent 0xd43dc7558f1678cb40ecef97f93608186021b7b5ba05855d58270329f018dd96    
2024-03-12 21:11:54 🎁 Prepared block for proposing at 1648 (1 ms) [hash: 0xced73b8ae7792bcfe48e520cd1c023af5e42c15395948c8460546cff95cce7ee; parent_hash: 0xd43d…dd96; extrinsics (2): [0xbbc0…2695, 0x0375…2dd6]    
2024-03-12 21:11:54 🔖 Pre-sealed block for proposal at 1648. Hash now 0x1385fde2ca7902a4eb911200dbef94ea523cf4941ecb93aee90de2acb131aedc, previously 0xced73b8ae7792bcfe48e520cd1c023af5e42c15395948c8460546cff95cce7ee.    
2024-03-12 21:11:54 ✨ Imported #1648 (0x1385…aedc)    
2024-03-12 21:11:57 💤 Idle (0 peers), best: #1648 (0x1385…aedc), finalized #1646 (0x2a82…98e5), ⬇ 0 ⬆ 0    
2024-03-12 21:12:00 🙌 Starting consensus session on top of parent 0x1385fde2ca7902a4eb911200dbef94ea523cf4941ecb93aee90de2acb131aedc    
2024-03-12 21:12:00 🎁 Prepared block for proposing at 1649 (2 ms) [hash: 0x8f4829797007fc41f6d350db3af09cbf7f9ede31c733e48b15bc309e1ac3bf24; parent_hash: 0x1385…aedc; extrinsics (2): [0x8be7…349f, 0x0375…2dd6]    
2024-03-12 21:12:00 🔖 Pre-sealed block for proposal at 1649. Hash now 0x6a0ceb578241b2fa75b93f376c0f7275274ac0e9524d4fe41a8078d09855e7bf, previously 0x8f4829797007fc41f6d350db3af09cbf7f9ede31c733e48b15bc309e1ac3bf24.    
2024-03-12 21:12:00 ✨ Imported #1649 (0x6a0c…e7bf)    
2024-03-12 21:12:02 💤 Idle (0 peers), best: #1649 (0x6a0c…e7bf), finalized #1647 (0xd43d…dd96), ⬇ 0 ⬆ 0    
2024-03-12 21:12:06 🙌 Starting consensus session on top of parent 0x6a0ceb578241b2fa75b93f376c0f7275274ac0e9524d4fe41a8078d09855e7bf    
2024-03-12 21:12:06 🎁 Prepared block for proposing at 1650 (3 ms) [hash: 0x5fffcbe0e7653027e4cd8092529b9a1f9c452a0eb7cac7fdfc6f91e3565096d4; parent_hash: 0x6a0c…e7bf; extrinsics (2): [0xbeb4…47ac, 0x0375…2dd6]    
2024-03-12 21:12:06 🔖 Pre-sealed block for proposal at 1650. Hash now 0xaef7e1693183b85bd67aba3311be50a48cdd6d2119046fd02fb7aaff7a668833, previously 0x5fffcbe0e7653027e4cd8092529b9a1f9c452a0eb7cac7fdfc6f91e3565096d4.    
2024-03-12 21:12:06 ✨ Imported #1650 (0xaef7…8833)    
2024-03-12 21:12:07 💤 Idle (0 peers), best: #1650 (0xaef7…8833), finalized #1648 (0x1385…aedc), ⬇ 0 ⬆ 0    
2024-03-12 21:12:12 🙌 Starting consensus session on top of parent 0xaef7e1693183b85bd67aba3311be50a48cdd6d2119046fd02fb7aaff7a668833    
2024-03-12 21:12:12 🎁 Prepared block for proposing at 1651 (3 ms) [hash: 0x20e56759393783561dd4a35a7a76a8c644a6025147125baf9bb02b399666f416; parent_hash: 0xaef7…8833; extrinsics (2): [0xeebe…2927, 0x0375…2dd6]    
2024-03-12 21:12:12 🔖 Pre-sealed block for proposal at 1651. Hash now 0x8c536da2edfbc5f0101b2954f1263bb9b2c9048716234a71e97ce0958acaab5b, previously 0x20e56759393783561dd4a35a7a76a8c644a6025147125baf9bb02b399666f416.    
2024-03-12 21:12:12 ✨ Imported #1651 (0x8c53…ab5b)    
2024-03-12 21:12:12 💤 Idle (0 peers), best: #1651 (0x8c53…ab5b), finalized #1648 (0x1385…aedc), ⬇ 0 ⬆ 0    
2024-03-12 21:12:17 💤 Idle (0 peers), best: #1651 (0x8c53…ab5b), finalized #1649 (0x6a0c…e7bf), ⬇ 0 ⬆ 0    
2024-03-12 21:12:18 🙌 Starting consensus session on top of parent 0x8c536da2edfbc5f0101b2954f1263bb9b2c9048716234a71e97ce0958acaab5b    
2024-03-12 21:12:18 🎁 Prepared block for proposing at 1652 (2 ms) [hash: 0x05c0784f9830ee02604271494619c4b4a7912aadb5dd3c3caf0fc46213382d99; parent_hash: 0x8c53…ab5b; extrinsics (2): [0x7f07…64c0, 0x0375…2dd6]    
2024-03-12 21:12:18 🔖 Pre-sealed block for proposal at 1652. Hash now 0x3c020ad52e3b2350f83542ef36f0ac9a14e29f7905a88dede8e8d285476fdad8, previously 0x05c0784f9830ee02604271494619c4b4a7912aadb5dd3c3caf0fc46213382d99.    
2024-03-12 21:12:18 ✨ Imported #1652 (0x3c02…dad8)    
2024-03-12 21:12:22 💤 Idle (0 peers), best: #1652 (0x3c02…dad8), finalized #1650 (0xaef7…8833), ⬇ 0 ⬆ 0    
2024-03-12 21:12:24 🙌 Starting consensus session on top of parent 0x3c020ad52e3b2350f83542ef36f0ac9a14e29f7905a88dede8e8d285476fdad8    
2024-03-12 21:12:24 🎁 Prepared block for proposing at 1653 (2 ms) [hash: 0x9e17ffc25ba6a4c791984c7c15fb8c34e2791ece0e4daa43506ae6dc2366e4a7; parent_hash: 0x3c02…dad8; extrinsics (2): [0x60f8…61bb, 0x0375…2dd6]    
2024-03-12 21:12:24 🔖 Pre-sealed block for proposal at 1653. Hash now 0x4aa98f0817b630fe1b65d6013303a65a3da8e7ab1a36213734ecd0cb804c80ba, previously 0x9e17ffc25ba6a4c791984c7c15fb8c34e2791ece0e4daa43506ae6dc2366e4a7.    
2024-03-12 21:12:24 ✨ Imported #1653 (0x4aa9…80ba)    
2024-03-12 21:12:27 💤 Idle (0 peers), best: #1653 (0x4aa9…80ba), finalized #1651 (0x8c53…ab5b), ⬇ 0 ⬆ 0    
2024-03-12 21:12:30 🙌 Starting consensus session on top of parent 0x4aa98f0817b630fe1b65d6013303a65a3da8e7ab1a36213734ecd0cb804c80ba    
2024-03-12 21:12:30 🎁 Prepared block for proposing at 1654 (1 ms) [hash: 0x228e0a27cf094ee43c80ca3f01b38f26485346efd05a3b302b96b812fcbca5e5; parent_hash: 0x4aa9…80ba; extrinsics (2): [0xb334…b40a, 0x0375…2dd6]    
2024-03-12 21:12:30 🔖 Pre-sealed block for proposal at 1654. Hash now 0x5675c9d1d0e3efeee47bf26a82e02ed64f3a80e22b6e6afd0314711d0f3cbdb2, previously 0x228e0a27cf094ee43c80ca3f01b38f26485346efd05a3b302b96b812fcbca5e5.    
2024-03-12 21:12:30 ✨ Imported #1654 (0x5675…bdb2)    
2024-03-12 21:12:30 Accepting new connection 1/100
2024-03-12 21:12:32 💤 Idle (0 peers), best: #1654 (0x5675…bdb2), finalized #1652 (0x3c02…dad8), ⬇ 0 ⬆ 0    
2024-03-12 21:12:36 🙌 Starting consensus session on top of parent 0x5675c9d1d0e3efeee47bf26a82e02ed64f3a80e22b6e6afd0314711d0f3cbdb2    
2024-03-12 21:12:36 🎁 Prepared block for proposing at 1655 (1 ms) [hash: 0xe7ecbb798b7394a3657d195b54fab0cba245ca8750e7ae91e0047bac94115ba5; parent_hash: 0x5675…bdb2; extrinsics (2): [0x80a7…9372, 0x0375…2dd6]    
2024-03-12 21:12:36 🔖 Pre-sealed block for proposal at 1655. Hash now 0x199bd46dae01a02ce57c8e21be171d528388b73edc3c9d38dcada1f25d5e5fcd, previously 0xe7ecbb798b7394a3657d195b54fab0cba245ca8750e7ae91e0047bac94115ba5.    
2024-03-12 21:12:36 ✨ Imported #1655 (0x199b…5fcd)    
2024-03-12 21:12:37 💤 Idle (0 peers), best: #1655 (0x199b…5fcd), finalized #1653 (0x4aa9…80ba), ⬇ 0 ⬆ 0    
2024-03-12 21:12:42 🙌 Starting consensus session on top of parent 0x199bd46dae01a02ce57c8e21be171d528388b73edc3c9d38dcada1f25d5e5fcd    
2024-03-12 21:12:42 🎁 Prepared block for proposing at 1656 (1 ms) [hash: 0xfd947cdf2ea6bf57e3faa1be8e07742a3f4ca4c4fa7a7721c83a91b9ce664133; parent_hash: 0x199b…5fcd; extrinsics (2): [0x15ff…44ce, 0x0375…2dd6]    
2024-03-12 21:12:42 🔖 Pre-sealed block for proposal at 1656. Hash now 0xfc8e13decf3b0d2399d2b234c40a554f5d41ebe468f96c7e98a5e80a03fcbf93, previously 0xfd947cdf2ea6bf57e3faa1be8e07742a3f4ca4c4fa7a7721c83a91b9ce664133.    
2024-03-12 21:12:42 ✨ Imported #1656 (0xfc8e…bf93)    
2024-03-12 21:12:42 💤 Idle (0 peers), best: #1656 (0xfc8e…bf93), finalized #1653 (0x4aa9…80ba), ⬇ 0 ⬆ 0    
2024-03-12 21:12:47 💤 Idle (0 peers), best: #1656 (0xfc8e…bf93), finalized #1654 (0x5675…bdb2), ⬇ 0 ⬆ 0    
2024-03-12 21:12:48 🙌 Starting consensus session on top of parent 0xfc8e13decf3b0d2399d2b234c40a554f5d41ebe468f96c7e98a5e80a03fcbf93    
2024-03-12 21:12:48 🎁 Prepared block for proposing at 1657 (2 ms) [hash: 0x02345858335caa5cc8cb1e176876d0f8c36c5fe873a074388e6af62471ca6a58; parent_hash: 0xfc8e…bf93; extrinsics (2): [0xaa88…25c2, 0x0375…2dd6]    
2024-03-12 21:12:48 🔖 Pre-sealed block for proposal at 1657. Hash now 0xe8aa14e07a35b70d1de077832d080e036a8c0d670eef1864d8c3f8bd7cfe88f3, previously 0x02345858335caa5cc8cb1e176876d0f8c36c5fe873a074388e6af62471ca6a58.    
2024-03-12 21:12:48 ✨ Imported #1657 (0xe8aa…88f3)    
2024-03-12 21:12:49 Accepting new connection 1/100
2024-03-12 21:12:49 Accepting new connection 2/100
2024-03-12 21:12:49 [1657] 🐺 failed to call smart contract PreExecutionError(EntryPointNotFound(EntryPointSelector(StarkFelt("0x01a35984e05126dbecb7c3bb9929e7dd9106d460c59b1633739a5c733a5fb13b"))))    
2024-03-12 21:12:49 Accepting new connection 2/100
2024-03-12 21:12:52 💤 Idle (0 peers), best: #1657 (0xe8aa…88f3), finalized #1655 (0x199b…5fcd), ⬇ 0 ⬆ 0    
2024-03-12 21:12:54 🙌 Starting consensus session on top of parent 0xe8aa14e07a35b70d1de077832d080e036a8c0d670eef1864d8c3f8bd7cfe88f3    
2024-03-12 21:12:54 🎁 Prepared block for proposing at 1658 (1 ms) [hash: 0x047c632c6f1832c4900467ea5e6f84990a19fc13d50a4de1bd87a5e35b68022c; parent_hash: 0xe8aa…88f3; extrinsics (2): [0x2eee…58a1, 0x0375…2dd6]    
2024-03-12 21:12:54 🔖 Pre-sealed block for proposal at 1658. Hash now 0x20a50937b137d747f3568cf734f978d50a0fc9c4ef20aabdc218739572345129, previously 0x047c632c6f1832c4900467ea5e6f84990a19fc13d50a4de1bd87a5e35b68022c.    
2024-03-12 21:12:54 ✨ Imported #1658 (0x20a5…5129)    
2024-03-12 21:12:55 Accepting new connection 2/100
2024-03-12 21:12:55 Accepting new connection 2/100
2024-03-12 21:12:57 Accepting new connection 2/100
2024-03-12 21:12:57 Accepting new connection 2/100
2024-03-12 21:12:57 💤 Idle (0 peers), best: #1658 (0x20a5…5129), finalized #1656 (0xfc8e…bf93), ⬇ 0 ⬆ 0    
2024-03-12 21:13:00 🙌 Starting consensus session on top of parent 0x20a50937b137d747f3568cf734f978d50a0fc9c4ef20aabdc218739572345129    
2024-03-12 21:13:00 🎁 Prepared block for proposing at 1659 (2 ms) [hash: 0x72078a206a9265b6719423658ba3785a160948521890303964cbaa87008e3254; parent_hash: 0x20a5…5129; extrinsics (2): [0x6764…e884, 0x0375…2dd6]    
2024-03-12 21:13:00 🔖 Pre-sealed block for proposal at 1659. Hash now 0xcff849f4cea12c87a70868b9ac40dfb1da7ac8172edef65aeaecdec13f9b5e4e, previously 0x72078a206a9265b6719423658ba3785a160948521890303964cbaa87008e3254.    
2024-03-12 21:13:00 ✨ Imported #1659 (0xcff8…5e4e)    
2024-03-12 21:13:02 Accepting new connection 2/100
2024-03-12 21:13:02 Accepting new connection 2/100
2024-03-12 21:13:02 💤 Idle (0 peers), best: #1659 (0xcff8…5e4e), finalized #1657 (0xe8aa…88f3), ⬇ 0 ⬆ 0    
2024-03-12 21:13:03 Accepting new connection 2/100
2024-03-12 21:13:03 Failed to retrieve contract class from hash '0x04afd993d1327dcae9a307a91447b62537ca1f683ed78757f25cecc19e05b4de'    
2024-03-12 21:13:03 Accepting new connection 2/100
2024-03-12 21:13:04 Accepting new connection 2/100
2024-03-12 21:13:04 Failed to convert BroadcastedDeclareTransaction to UserTransaction, error: Failed to compile to Sierra    
2024-03-12 21:13:06 🙌 Starting consensus session on top of parent 0xcff849f4cea12c87a70868b9ac40dfb1da7ac8172edef65aeaecdec13f9b5e4e    
2024-03-12 21:13:06 🎁 Prepared block for proposing at 1660 (4 ms) [hash: 0xc69c7a5acb09376db6715ee8d60a40a11133d8bd5a4a8f601f5775bd3d7315f4; parent_hash: 0xcff8…5e4e; extrinsics (2): [0xd5de…677b, 0x0375…2dd6]    
2024-03-12 21:13:06 🔖 Pre-sealed block for proposal at 1660. Hash now 0x4f701e0cbc5e7d6535d5a110b021fb0062d68134eada1009746c84d4a018410e, previously 0xc69c7a5acb09376db6715ee8d60a40a11133d8bd5a4a8f601f5775bd3d7315f4.    
2024-03-12 21:13:06 ✨ Imported #1660 (0x4f70…410e)    
2024-03-12 21:13:07 💤 Idle (0 peers), best: #1660 (0x4f70…410e), finalized #1658 (0x20a5…5129), ⬇ 0 ⬆ 0
```

Seems declare v2 transaction failed for Precompiles program

### Expected behavior

The kakarot programs deployed

### Steps to reproduce

Create Madara app chain with karnot CLI w/o DA and Settlement layer. 
Clone the kakarot repo and apply patch for correct script interaction with madara RPC
```
diff --git a/scripts/utils/starknet.py b/scripts/utils/starknet.py
index 0e80998..9a9c355 100644
--- a/scripts/utils/starknet.py
+++ b/scripts/utils/starknet.py
@@ -97,6 +97,7 @@ async def get_starknet_account(
         except Exception as err:
             message = str(err)
             if (
+                "Client failed with code 40. Message: Contract error." in message or
                 "Client failed with code 40: Contract error." in message
                 or "Client failed with code 40: Requested entry point was not found."
                 in message

```
Execute `make deploy` command to run deploy script

### Other information

[Kakarot SSJ programs compiled with Cairo v2.4.0](https://github.com/kkrt-labs/kakarot-ssj/blob/main/Scarb.toml)
[While Madara latest supported version is 2.1.0](https://t.me/MadaraStarknet/15442)

The deployment process worked well with katana node deployed with kakarot scripts

**Comment by enitrat** [comment]
Hi! 
Unfortunately we can't compile Kakarot SSJ (precompiles) with Cairo <2.4 (or even 2.5). This is an issue for Madara rather than for us, but AFAIK they're working on updating this.

Thanks for reporting this, if you have any other questions, let us know!
